-- MySQL Script generated by MySQL Workbench
-- Mon Sep 19 21:02:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Auto garage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Auto garage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Auto garage` DEFAULT CHARACTER SET utf8 ;
USE `Auto garage` ;

-- -----------------------------------------------------
-- Table `Auto garage`.`Cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Auto garage`.`Cars` (
  `idCars` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(20) NOT NULL,
  `model` VARCHAR(20) NOT NULL,
  `yearOfIssue` INT NOT NULL,
  `mileage` DECIMAL(10,2) NOT NULL,
  `stateNumber` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idCars`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Auto garage`.`Drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Auto garage`.`Drivers` (
  `idDrivers` INT NOT NULL AUTO_INCREMENT,
  `fullName` VARCHAR(90) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `address` VARCHAR(120) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `callCode` VARCHAR(30) NOT NULL,
  `dateOfBirth` DATE NOT NULL,
  `experience` INT NOT NULL,
  PRIMARY KEY (`idDrivers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Auto garage`.`Traffics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Auto garage`.`Traffics` (
  `idTraffics` INT NOT NULL AUTO_INCREMENT,
  `startPoint` VARCHAR(120) NOT NULL,
  `endPoint` VARCHAR(120) NOT NULL,
  `trafficLength` INT NOT NULL,
  `countStops` INT NOT NULL,
  `idCars` INT NOT NULL,
  `idDrivers` INT NOT NULL,
  PRIMARY KEY (`idTraffics`),
  INDEX `cars_idx` (`idCars` ASC) VISIBLE,
  INDEX `drivers_idx` (`idDrivers` ASC) VISIBLE,
  CONSTRAINT `cars`
    FOREIGN KEY (`idCars`)
    REFERENCES `Auto garage`.`Cars` (`idCars`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `drivers`
    FOREIGN KEY (`idDrivers`)
    REFERENCES `Auto garage`.`Drivers` (`idDrivers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


SELECT * FROM cars