-- MySQL Script generated by MySQL Workbench
-- Mon Nov 21 18:10:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DEALERSHIP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DEALERSHIP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DEALERSHIP` DEFAULT CHARACTER SET utf8 ;
USE `DEALERSHIP` ;

-- -----------------------------------------------------
-- Table `DEALERSHIP`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEALERSHIP`.`Clients` (
  `ID_clients` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `series_numbers_passport` VARCHAR(30) NOT NULL,
  `passport_issue` VARCHAR(30) NOT NULL,
  `data_issue` DATE NOT NULL,
  `phone` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID_clients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEALERSHIP`.`Managers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEALERSHIP`.`Managers` (
  `ID_manager` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `series_numbers_passport` VARCHAR(30) NOT NULL,
  `passport_issue` VARCHAR(30) NOT NULL,
  `data_issue` DATE NOT NULL,
  `data_of_birth` DATE NOT NULL,
  `gender` VARCHAR(30) NULL,
  `phone` VARCHAR(30) NOT NULL,
  `salary` INT NOT NULL,
  PRIMARY KEY (`ID_manager`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEALERSHIP`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEALERSHIP`.`Brands` (
  `ID_brands` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID_brands`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEALERSHIP`.`Auto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEALERSHIP`.`Auto` (
  `ID_auto` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(30) NOT NULL,
  `color` VARCHAR(30) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `made_in` VARCHAR(30) NOT NULL,
  `transmission` VARCHAR(30) NOT NULL,
  `signaling` TINYINT(1) NOT NULL,
  `ID_brands` INT NOT NULL,
  PRIMARY KEY (`ID_auto`),
  INDEX `brands_idx` (`ID_brands` ASC) VISIBLE,
  CONSTRAINT `brands`
    FOREIGN KEY (`ID_brands`)
    REFERENCES `DEALERSHIP`.`Brands` (`ID_brands`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEALERSHIP`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEALERSHIP`.`Addresses` (
  `ID_addresses` INT NOT NULL AUTO_INCREMENT,
  `adress` VARCHAR(45) NOT NULL,
  `city` VARCHAR(30) NOT NULL,
  `phone` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID_addresses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEALERSHIP`.`Filials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEALERSHIP`.`Filials` (
  `ID_filials` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `full_name_admin` VARCHAR(45) NOT NULL,
  `ID_adresses` INT NOT NULL,
  PRIMARY KEY (`ID_filials`),
  INDEX `adress_idx` (`ID_adresses` ASC) VISIBLE,
  CONSTRAINT `adress`
    FOREIGN KEY (`ID_adresses`)
    REFERENCES `DEALERSHIP`.`Addresses` (`ID_addresses`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DEALERSHIP`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEALERSHIP`.`Orders` (
  `ID_orders` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(10,2) NOT NULL,
  `delivery_period` VARCHAR(30) NOT NULL,
  `data_registration` DATE NOT NULL,
  `ID_clients` INT NOT NULL,
  `ID_manager` INT NOT NULL,
  `ID_filials` INT NOT NULL,
  `ID_auto` INT NOT NULL,
  PRIMARY KEY (`ID_orders`),
  INDEX `managers_idx` (`ID_manager` ASC) VISIBLE,
  INDEX `clients_idx` (`ID_clients` ASC) VISIBLE,
  INDEX `auto_idx` (`ID_auto` ASC) VISIBLE,
  INDEX `filials_idx` (`ID_filials` ASC) VISIBLE,
  CONSTRAINT `managers`
    FOREIGN KEY (`ID_manager`)
    REFERENCES `DEALERSHIP`.`Managers` (`ID_manager`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `clients`
    FOREIGN KEY (`ID_clients`)
    REFERENCES `DEALERSHIP`.`Clients` (`ID_clients`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `auto`
    FOREIGN KEY (`ID_auto`)
    REFERENCES `DEALERSHIP`.`Auto` (`ID_auto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `filials`
    FOREIGN KEY (`ID_filials`)
    REFERENCES `DEALERSHIP`.`Filials` (`ID_filials`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
